/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'jo-icons\'">' + entity + '</span>' + html;
	}
	var icons = {
		'joicon-accounts': '&#xe600;',
		'joicon-add': '&#xe601;',
		'joicon-alert': '&#xe602;',
		'joicon-assets': '&#xe603;',
		'joicon-attachment': '&#xe604;',
		'joicon-autoresponder': '&#xe605;',
		'joicon-bell': '&#xe606;',
		'joicon-bulb': '&#xe607;',
		'joicon-calendar': '&#xe608;',
		'joicon-calendaragenda': '&#xe609;',
		'joicon-calendarlist': '&#xe60a;',
		'joicon-call': '&#xe60b;',
		'joicon-camera': '&#xe60c;',
		'joicon-campaigns': '&#xe60d;',
		'joicon-cases': '&#xe60e;',
		'joicon-chat': '&#xe60f;',
		'joicon-close': '&#xe610;',
		'joicon-code': '&#xe611;',
		'joicon-codebraces': '&#xe612;',
		'joicon-cog': '&#xe613;',
		'joicon-columns': '&#xe614;',
		'joicon-compose': '&#xe615;',
		'joicon-contacts': '&#xe616;',
		'joicon-customerportal': '&#xe617;',
		'joicon-default': '&#xe618;',
		'joicon-detailreport': '&#xe619;',
		'joicon-documents': '&#xe61a;',
		'joicon-duplicaterecords': '&#xe61b;',
		'joicon-edit': '&#xe61c;',
		'joicon-emailcampaigns': '&#xe61d;',
		'joicon-emails': '&#xe61e;',
		'joicon-emailtemplates': '&#xe61f;',
		'joicon-engagementhistory': '&#xe620;',
		'joicon-equalizer': '&#xe621;',
		'joicon-esign': '&#xe622;',
		'joicon-exit': '&#xe623;',
		'joicon-export': '&#xe624;',
		'joicon-eyeclose': '&#xe625;',
		'joicon-eyeopen': '&#xe626;',
		'joicon-faq': '&#xe627;',
		'joicon-fb': '&#xe628;',
		'joicon-folderclose': '&#xe629;',
		'joicon-foldermove': '&#xe62a;',
		'joicon-folderopen': '&#xe62b;',
		'joicon-forecast': '&#xe62c;',
		'joicon-forward': '&#xe62d;',
		'joicon-googleplus': '&#xe62e;',
		'joicon-graphview': '&#xe62f;',
		'joicon-grid': '&#xe630;',
		'joicon-help': '&#xe631;',
		'joicon-helpdesk': '&#xe632;',
		'joicon-home': '&#xe633;',
		'joicon-image': '&#xe634;',
		'joicon-import': '&#xe635;',
		'joicon-insights': '&#xe636;',
		'joicon-inventory': '&#xe637;',
		'joicon-inventory2': '&#xe638;',
		'joicon-inventory3': '&#xe639;',
		'joicon-invoice': '&#xe63a;',
		'joicon-invoicerecurring': '&#xe63b;',
		'joicon-leads': '&#xe63c;',
		'joicon-link': '&#xe63d;',
		'joicon-linkopen': '&#xe63e;',
		'joicon-list': '&#xe63f;',
		'joicon-lock': '&#xe640;',
		'joicon-lockopen': '&#xe641;',
		'joicon-logout': '&#xe642;',
		'joicon-mailmanager': '&#xe643;',
		'joicon-mandatory': '&#xe644;',
		'joicon-marketinglist': '&#xe645;',
		'joicon-massedit': '&#xe646;',
		'joicon-meeting': '&#xe647;',
		'joicon-move': '&#xe648;',
		'joicon-mycalendar': '&#xe649;',
		'joicon-olark': '&#xe64a;',
		'joicon-olark2': '&#xe64b;',
		'joicon-oursites': '&#xe64c;',
		'joicon-pagecount': '&#xe64d;',
		'joicon-payments': '&#xe64e;',
		'joicon-pbxmanager': '&#xe64f;',
		'joicon-phonecalls': '&#xe650;',
		'joicon-pin': '&#xe651;',
		'joicon-pivots': '&#xe652;',
		'joicon-play': '&#xe653;',
		'joicon-potentials': '&#xe654;',
		'joicon-pricebooks': '&#xe655;',
		'joicon-printtemplates': '&#xe656;',
		'joicon-products': '&#xe657;',
		'joicon-project': '&#xe658;',
		'joicon-projectmilestone': '&#xe659;',
		'joicon-projecttask': '&#xe65a;',
		'joicon-purchaseorder': '&#xe65b;',
		'joicon-puzzle': '&#xe65c;',
		'joicon-quickbooks': '&#xe65d;',
		'joicon-quotes': '&#xe65e;',
		'joicon-recyclebin': '&#xe65f;',
		'joicon-refresh': '&#xe660;',
		'joicon-replytoall': '&#xe661;',
		'joicon-reports': '&#xe662;',
		'joicon-restorerecyclebin': '&#xe663;',
		'joicon-retweet': '&#xe664;',
		'joicon-road': '&#xe665;',
		'joicon-rss': '&#xe666;',
		'joicon-salesorder': '&#xe667;',
		'joicon-search': '&#xe668;',
		'joicon-selectcolumn': '&#xe669;',
		'joicon-servicecontracts': '&#xe66a;',
		'joicon-services': '&#xe66b;',
		'joicon-share': '&#xe66c;',
		'joicon-sharedcalendar': '&#xe66d;',
		'joicon-shoppingcart': '&#xe66e;',
		'joicon-smiley1': '&#xe66f;',
		'joicon-smiley2': '&#xe670;',
		'joicon-smiley3': '&#xe671;',
		'joicon-smsnotifier': '&#xe672;',
		'joicon-social': '&#xe673;',
		'joicon-starempty': '&#xe674;',
		'joicon-starfull': '&#xe675;',
		'joicon-starhalf': '&#xe676;',
		'joicon-subscription': '&#xe677;',
		'joicon-tag': '&#xe678;',
		'joicon-task': '&#xe679;',
		'joicon-taxes': '&#xe67a;',
		'joicon-timeline': '&#xe67b;',
		'joicon-toggle': '&#xe67c;',
		'joicon-transactions': '&#xe67d;',
		'joicon-twitter': '&#xe67e;',
		'joicon-twitterreply': '&#xe67f;',
		'joicon-unpin': '&#xe680;',
		'joicon-unplug': '&#xe681;',
		'joicon-vendors': '&#xe682;',
		'joicon-vendors3': '&#xe683;',
		'joicon-video': '&#xe684;',
		'joicon-volumeoff': '&#xe685;',
		'joicon-volumeon': '&#xe686;',
		'joicon-vtigeruser': '&#xe687;',
		'joicon-vtigeruser2': '&#xe688;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/joicon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
